name:
on:
  push:
    branches: [ "main" ]
env:
  app_version: 2.2.2
  app_plugins: ep_font_size ep_font_family ep_font_color ep_spellcheck ep_table_of_contents ep_subscript_and_superscript ep_mammoth ep_print ep_comments_page ep_embedded_hyperlinks2 ep_adminpads2 ep_align ep_headings2 ep_cursortrace ep_markdown ep_set_title_on_pad ep_embedmedia ep_themes ep_rewrite_share_paths
permissions:
  checks: write
  contents: write
  packages: write
  pull-requests: read
jobs:
  build-publish:
    name: Build and Publish
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
            registry.etke.cc/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref_name == 'main' }}
            type=raw,value=${{ env.app_version }},enable=${{ github.ref_name == 'main' }}
      - name: Checkout Etherpad
        container: git
        run: |
          wget https://github.com/ether/etherpad-lite/archive/refs/tags/v${{ env.app_version }}.tar.gz
          tar -xf ${{ env.app_version }}.tar.gz
          mv ${{ env.app_version }} etherpad-lite
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ETHERPAD_PLUGINS=${{ env.app_plugins }}
            INSTALL_SOFFICE=true
